// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using JetStreamCommons;
using JetStreamCommons.SearchAirports;
using Sitecore.MobileSDK.API.Items;



namespace JetStreamIOS
{
	public partial class SearchAirportTableViewController : UIViewController
	{
		public SearchAirportTableViewController (IntPtr handle) : base (handle)
		{
		}

    #region UIViewController
    public override void ViewDidLoad()
    {
      base.ViewDidLoad ();

      this.tableViewSource = new SearchAirportsSource();
      this.TableView.Source = this.tableViewSource;

      this.tableViewDelegate = new SearchAirportsDelegate();
      this.tableViewDelegate.AirportsTable = this;
      this.TableView.Delegate = this.tableViewDelegate;

      this.searchBarDelegate = new AirportsSearchBarDelegate();
      this.searchBarDelegate.AirportsTable = this;
      this.SearchBar.Delegate = this.searchBarDelegate;

      this.GetAllAirports();
    }

    public override void ViewWillAppear(bool animated)
    {
      base.ViewWillAppear(animated);

      if (null == this.SearchTicketsBuilder)
      {
        throw new ArgumentNullException();
      }

      this.SearchBar.Text = this.SourceTextField.Text;
    }
    #endregion


    private async Task<ScItemsResponse> DownloadAllAirportsAnimated()
    {
      this.ShowLoader();

      try
      {
        // It will automatically get values from the NSUserDefaults singleton
        var endpoint = new InstanceSettings();

        // It will be disposed by RestManager
        var session = endpoint.GetSession();
        using (var restManager = new RestManager(session))
        {
          return await restManager.SearchAllAirports();
        }
      }
      catch
      {
        AlertHelper.ShowAlertWithOkOption("Failure", "Unable to download airports");
        return null;
      }
      finally
      {
        this.HideLoader();
      }
    }

    private async void GetAllAirports()
    {
      this.AllAirportsList = await this.DownloadAllAirportsAnimated();

      if (null == this.AllAirportsList)
      {
        return;
      }
      else if (this.AllAirportsList.ResultCount == 0)
      {
        AlertHelper.ShowAlertWithOkOption("Failure", "No Airports Found");
        return;
      }


      // triggers UITableView
      this.SearchAirportsAndUpdateTable();
    }

    public void SearchAirportsAndUpdateTable()
    {
      string stringToSearch = this.SearchBar.Text.ToLowerInvariant();

      var searchEngine = new AirportsCaseInsensitiveSearchEngine(stringToSearch);
      IEnumerable<ISitecoreItem> searchResult = searchEngine.SearchAirports(this.AllAirportsList);
      this.ResultList = searchResult.ToList();

      this.tableViewSource.Items = this.ResultList;
      this.TableView.ReloadData();
    }

    public void HideSearchKeyboard()
    {
      this.SearchBar.ResignFirstResponder();
    }

    #region UITableViewDelegate
    public void RowSelected(int row)
    {
      ISitecoreItem selectedAirport = this.ResultList[row];

      string airportId = selectedAirport.Id;
      if (this.isFromAirportSearch)
      {
        this.SearchTicketsBuilder.Set.SourceAirport(airportId);
      }
      else
      {
        this.SearchTicketsBuilder.Set.DestinationAirport(airportId);
      }

      this.SourceTextField.Text = selectedAirport.DisplayName;
      this.NavigationController.PopViewControllerAnimated(true);
    }
    #endregion

    #region Progress indicator
    private void ShowLoader()
    {
      this.loadingOverlay = new LoadingOverlay (this.View.Bounds, NSBundle.MainBundle.LocalizedString ("Loading Data", null));
      this.View.Add (loadingOverlay);
    }

    private void HideLoader()
    {
      if (this.loadingOverlay != null)
      {
        this.loadingOverlay.Hide ();
      }
    }
    #endregion


    private SearchAirportsSource tableViewSource;
    private SearchAirportsDelegate tableViewDelegate;
    private AirportsSearchBarDelegate searchBarDelegate;

    private ScItemsResponse AllAirportsList;
    private List<ISitecoreItem> ResultList;
    private LoadingOverlay loadingOverlay;

    public UITextField SourceTextField;
    public SearchTicketsRequestBuilder SearchTicketsBuilder;
    public bool isFromAirportSearch = true;
	}
}
