// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace JetStreamIOS
{
	public partial class FlightDetailsViewController : UIViewController
	{
		public FlightDetailsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
