// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace JetStreamIOS
{
	public partial class OrderSummaryViewController : UIView
	{
		public OrderSummaryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
