// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using JetStreamCommons;
using System.Collections;
using Sitecore.MobileSDK.API.Items;

namespace JetStreamIOS
{
	public partial class SearchViewController : UIViewController
	{
		public SearchViewController (IntPtr handle) : base (handle)
		{
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad ();
      this.GetAirports ();
    }

    private async void GetAirports()
    {
//      this.TitleLabel.Text = "*";
//      RestManager restManager = new RestManager ();
//      ScItemsResponse result = await restManager.GetFullAirportsList ();
//      this.TitleLabel.Text = result.TotalCount.ToString();
    }
	}
}
