// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using JetStreamCommons;
using JetStreamIOSFull.Helpers;
using JetStreamCommons.About;

namespace JetStreamIOSFull
{
  public partial class AboutViewController : BaseViewController
	{
		public AboutViewController (IntPtr handle) : base (handle)
		{
		}

    public async override void ViewDidLoad()
    {
      base.ViewDidLoad();

      this.TopImageView.Image = this.Appearance.AboutBackground;
      try
      {
        using (var session = this.Endpoint.GetSession())
        {
          using (var loader = new ContentLoader (session))
          {
            try
            {
              IAboutPageInfo info = await loader.LoadAboutInfo();
              this.TitleLabel.Text = info.TitlePlainText;
              this.WelcomeLabel.Text = info.SummaryPlainText;

              string clearedText = info.BodyPlainText.Replace(System.Environment.NewLine, " ");
              this.MaainTextField.Text = clearedText;
              this.MaainTextField.Font = UIFont.SystemFontOfSize(18);
              this.MaainTextField.TextAlignment = UITextAlignment.Justified;
            }
            catch(Exception ex)
            {
              AlertHelper.ShowLocalizedAlertWithOkOption("NETWORK_ERROR_TITLE", "CANNOT_DOWNLOAD_ABOUT_ITEM_ERROR");
              throw ex;
            }
          }
        }
      }
      catch
      {
        Console.WriteLine("network error");
      }

    }
     
	}
}
