// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using JetStreamCommons.Destinations;
using SDWebImage;
using CoreGraphics;
using JetStreamCommons;
using System.Collections;
using System.Collections.Generic;

namespace JetStreamIOSFull
{
  public partial class DestinationDetailsViewController : BaseViewController
	{
    private IDestination destination;
    
		public DestinationDetailsViewController (IntPtr handle) : base (handle)
		{
      
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();

      this.TopBarImage.Image = this.Appearance.NavigationBackgroundImage;

      UIImage image = UIImage.FromBundle("Images.xcassets/LeftArrow.png");
      this.BackButton.SetImage(image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate), UIControlState.Normal);

      UIImage decoration = UIImage.FromBundle("Images.xcassets/bant98.png");
      this.DecorationImage.Image = decoration;
   }

    private async void DownloadAttractions()
    {
      if (this.destination != null)
      {
        using (var session = this.Endpoint.GetSession())
        {
          using (var loader = new DestinationsLoader (session))
          {
            List<IAttraction> attractions = await loader.LoadAttractions(this.destination);
            this.ImagesTableView.Source = new DestinationImagesSource (attractions, this.Endpoint);
            this.ImagesTableView.ReloadData();
          }
        }
      }
    }

    partial void BackgroundViewTouched (Foundation.NSObject sender)
    {
      this.DismissModalViewController(true);
    }

    public void ShowDestinationDetails(IDestination destination)
    {
      if (destination == null)
      {
        throw new NullReferenceException("Destination must not be null");
      }
      this.destination = destination;
      this.DownloadAttractions();
    }

    public override void ViewWillAppear(bool animated)
    {
      base.ViewWillAppear(animated);

      this.FillScreesnWithDestinationInfo(this.destination);
    }

    private void FillScreesnWithDestinationInfo(IDestination destination)
    {
      this.TitleLabel.Text = destination.DisplayName;

      this.DownloadAndShowDestinationImage(destination);

      string clearedText = destination.Overview.Replace(System.Environment.NewLine, " ");
      this.DestinationDescription.Text = clearedText;
      this.DestinationDescription.Font = UIFont.SystemFontOfSize(18);
      this.DestinationDescription.TextAlignment = UITextAlignment.Justified;
    }

    private void DownloadAndShowDestinationImage(IDestination destination)
    {
//      string imagePath = String.Concat(this.Endpoint.InstanceUrl, this.destination.ImagePath);
//
//      NSUrl imageUrl = new NSUrl(imagePath);
//
//      SDWebImageDownloader.SharedDownloader.DownloadImage(
//        url: imageUrl,
//        options: SDWebImageDownloaderOptions.LowPriority,
//        progressHandler: (receivedSize, expectedSize) =>
//      {
//        // Track progress...
//      },
//        completedHandler: (image, data, error, finished) =>
//      {
//        if (image != null)
//        {
//          InvokeOnMainThread(() =>
//          {
//            this.DestinationImageView.Image = image;
//          });
//        }
//      }
//      );
    }
	}
}
