// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JetStreamIOSFull
{
	public partial class DestinationImageCell : UITableViewCell
	{
		public DestinationImageCell (IntPtr handle) : base (handle)
		{
		}

    public void SetImage(UIImage image)
    {
      this.DestinationImage.Image = image;
    }

    public UIActivityIndicatorView ActivityIndicator
    {
      get
      { 
        return this.LoadingIndicator;
      }
    }
	}
}
