// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JetStreamIOSFull
{
	public partial class MainMenuCell : UITableViewCell
	{
    private UIColor defaultTintColor = UIColor.Blue;
    private UIColor selectedTintColor = UIColor.White;

		public MainMenuCell (IntPtr handle) : base (handle)
		{
		}

    public UIColor SelectedTintColor
    {
      set
      { 
        this.selectedTintColor = value;
      }
    }

    public UIColor DefaultTintColor
    {
      set
      { 
        this.defaultTintColor = value;
      }
    }

    public virtual void SetSelected(bool selected, bool animated)
    {
      UIColor color = this.defaultTintColor;
      if (selected)
      {
        color = this.selectedTintColor;
      }

      this.ImageView.TintColor = color;
      this.TitleLabel.TextColor = color;
    }

    public string Title
    {
      set
      { 
        this.TitleLabel.Text = value;
      }
    }

    public UIImage Image
    {
      set
      { 
        this.ImageView.Image = value.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
      }
    }
	}
}
