// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JetStreamIOSFull
{
  public partial class CheckInViewController : BaseViewController
	{
		public CheckInViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
