// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using JetStreamIOSFull.BaseVC;

namespace JetStreamIOSFull.NOTIMPLEMENTED
{
  public partial class CheckInViewController : BaseViewController
	{
		public CheckInViewController (IntPtr handle) : base (handle)
		{
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();

      this.TopImageView.Image = this.Appearance.CheckIn.TopImage;
      this.TitleLabel.Text = "Check In";
    }
	}
}
