// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JetStreamIOSFull
{
  public partial class FlightStatusViewController : BaseViewController
	{
		public FlightStatusViewController (IntPtr handle) : base (handle)
		{
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();

      this.TopImageView.Image = this.Appearance.FlightStatus.TopImage;
      this.TitleLabel.Text = "Flight Status";
    }
	}
}
