#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JetstreamAndroid.Resource", IsApplication=true)]

namespace JetstreamAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int fragment_names_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int button1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button2 = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int button_save = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int checkBox_roundtrip = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int content_frame = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int drawer_layout = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int field_from_location = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int field_instance_login = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int field_instance_password = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int field_instance_url = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int field_to_location = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int left_drawer = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout3 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int spinner_classes = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int spinner_number_of_tickets = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_search = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int key_instance_url = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int key_login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int key_password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int text_default_instance_url = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int text_default_login = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int text_default_password = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
