#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JetstreamAndroid.Resource", IsApplication=true)]

namespace JetstreamAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int fragment_names_array = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int number_of_tickets = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ticket_class = 2131099650;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int button_depart_date = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int button_return_date = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int button_save = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int button_search_tickets = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int checkBox_roundtrip = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int content_frame = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int drawer_layout = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int field_from_location = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int field_instance_login = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int field_instance_password = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int field_instance_url = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int field_to_location = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int left_drawer = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int spinner_classes = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int spinner_number_of_tickets = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int textview_return_date = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int airport_form_threshold = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_search = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int key_instance_url = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int key_login = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int key_password = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int text_button_ok = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int text_default_instance_url = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int text_default_login = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int text_default_password = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
