#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JetstreamAndroid.Resource", IsApplication=true)]

namespace JetstreamAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int fragment_names_array = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int number_of_tickets = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ticket_class = 2131165186;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int default_text_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_indicator = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tab_selected_focused_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tab_selected_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tab_selected_pressed_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tab_unselected_focused_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_unselected_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tab_unselected_pressed_holo = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0016
			public const int button_depart_date = 2131361814;
			
			// aapt resource value: 0x7f0a000d
			public const int button_earliest_departure_time = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int button_latest_departure_time = 2131361807;
			
			// aapt resource value: 0x7f0a000a
			public const int button_order_ticket = 2131361802;
			
			// aapt resource value: 0x7f0a0018
			public const int button_return_date = 2131361816;
			
			// aapt resource value: 0x7f0a001f
			public const int button_save = 2131361823;
			
			// aapt resource value: 0x7f0a001b
			public const int button_search_tickets = 2131361819;
			
			// aapt resource value: 0x7f0a0006
			public const int button_template = 2131361798;
			
			// aapt resource value: 0x7f0a0010
			public const int checkBox_flight_wifi = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int checkBox_food_service = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int checkBox_personal_entertainment = 2131361809;
			
			// aapt resource value: 0x7f0a0015
			public const int checkBox_roundtrip = 2131361813;
			
			// aapt resource value: 0x7f0a0003
			public const int content_frame = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int drawer_layout = 2131361794;
			
			// aapt resource value: 0x7f0a0013
			public const int field_from_location = 2131361811;
			
			// aapt resource value: 0x7f0a001d
			public const int field_instance_login = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int field_instance_password = 2131361822;
			
			// aapt resource value: 0x7f0a001c
			public const int field_instance_url = 2131361820;
			
			// aapt resource value: 0x7f0a0014
			public const int field_to_location = 2131361812;
			
			// aapt resource value: 0x7f0a0022
			public const int filter = 2131361826;
			
			// aapt resource value: 0x7f0a0000
			public const int indicator = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int left_drawer = 2131361796;
			
			// aapt resource value: 0x7f0a000e
			public const int linearLayout = 2131361806;
			
			// aapt resource value: 0x7f0a0001
			public const int pager = 2131361793;
			
			// aapt resource value: 0x7f0a000b
			public const int seekBar_max_price = 2131361803;
			
			// aapt resource value: 0x7f0a001a
			public const int spinner_classes = 2131361818;
			
			// aapt resource value: 0x7f0a0019
			public const int spinner_number_of_tickets = 2131361817;
			
			// aapt resource value: 0x7f0a000c
			public const int textView_seekbar_value = 2131361804;
			
			// aapt resource value: 0x7f0a0021
			public const int textview_day_date = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int textview_day_price = 2131361824;
			
			// aapt resource value: 0x7f0a0009
			public const int textview_flight_arrival = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int textview_flight_depart = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int textview_flight_price = 2131361799;
			
			// aapt resource value: 0x7f0a0017
			public const int textview_return_date = 2131361815;
			
			// aapt resource value: 0x7f0a0005
			public const int webView_flight_details = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int airport_form_threshold = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_flights = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_webiew_teemplate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int flights_list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_filter = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int tab_item = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int flights = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int key_instance_url = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int key_login = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int key_password = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int text_arrival_time = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int text_button_apply_filter = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int text_button_clear_filter = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int text_button_ok = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int text_button_order = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int text_button_purchase = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int text_deaprt_time = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int text_default_database = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int text_default_instance_url = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int text_default_language = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int text_default_login = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int text_default_password = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int text_error_select_airport = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int text_filter_applied = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int text_filter_cleared = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int text_filter_title = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int text_instance_connect_failed = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int text_no_tickets = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int text_num_of_airpots_found = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int text_successful_instance_connect = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int text_tickets_purchased = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Widget = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Widget_TabPageIndicator = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
