// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace JetStreamIOS
{
	public partial class FlightListViewController : UIViewController
	{
		public FlightListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
