// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using JetStreamCommons.Flight;

namespace JetStreamIOS
{
	public partial class FlightCell : UITableViewCell
	{

    #region Events
    public delegate void OnFlightSelectedDelegate(IJetStreamFlight flight);

    public OnFlightSelectedDelegate OnFlightSelected { get; set; }

    partial void OrderButtonPressed (MonoTouch.Foundation.NSObject sender)
    {
      this.OnFlightSelected(this.flight);
    }

    #endregion Events


    #region Model
    private IJetStreamFlight flight;

    public static NSString StaticReuseIdentifier()
    {
      return new NSString("FlightCell");
    }


    public void SetModel(IJetStreamFlight flight)
    {
      this.flight = flight;

      this.PriceLabel.Text = flight.Price.ToString("C");

      string strDepartureTime = DateConverter.StringFromTimeForUI(flight.DepartureTime.ToLocalTime());
      string strArrivalTime = DateConverter.StringFromTimeForUI(flight.ArrivalTime.ToLocalTime());

      string departureFormat = NSBundle.MainBundle.LocalizedString("DEPARTURE_DATE_FORMAT", null);
      string arrivalFormat = NSBundle.MainBundle.LocalizedString("ARRIVAL_DATE_FORMAT", null);

      this.DepartureTimeLabel.Text = string.Format(departureFormat, strDepartureTime);
      this.ArrivalTimeLabel.Text = string.Format(arrivalFormat, strArrivalTime);
    }
    #endregion Model

    #region UITableViewCell
		public FlightCell (IntPtr handle) : base (handle)
		{
		}

    public FlightCell(UITableViewCellStyle style, NSString reuseIdentifier) : base(style, reuseIdentifier)
    {
    }
    #endregion UITableViewCell
	}
}
